name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm install

      - run: npm run build --if-present

      - name: Debug environment
        env:
          PAYSTACK_SECRET_KEY: ${{ secrets.PAYSTACK_SECRET_KEY }}
        run: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "PAYSTACK_SECRET_KEY exists: $([[ -n "$PAYSTACK_SECRET_KEY" ]] && echo "yes" || echo "no")"
          echo "PAYSTACK_SECRET_KEY length: ${#PAYSTACK_SECRET_KEY}"
          echo "Key starts with sk_test: $([[ "$PAYSTACK_SECRET_KEY" == sk_test_* ]] && echo "yes" || echo "no")"
          echo "Environment variables count: $(env | wc -l)"
          echo "CI variable: $CI"
          echo "NODE_ENV: $NODE_ENV"

      - name: Run Integration Tests
        env:
          PAYSTACK_SECRET_KEY: ${{ secrets.PAYSTACK_SECRET_KEY }}
          NODE_ENV: test
        run: npm test -- --verbose --detectOpenHandles
